dist: trusty
sudo: required

language: scala

scala:
  - 2.11.7

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - psql -c 'create database ahdb;' -U ahuser -p p4ssw0rd