dist: trusty
sudo: required

language: scala

scala:
  - 2.11.7

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

jdk:
  - oraclejdk8

services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c 'create database ahdb;' -U postgres
  - psql -c "CREATE USER ahuser WITH PASSWORD 'p4ssw0rd';" -U postgres